### ISSUE TITLE
Bad recall from ODFE1.8 

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#154]
Problem:- 
Bad recall with repeated scores for vectors with different magnitude.

Issue:-
Elasticsearch upgraded Lucene version to 8.5.1 from 7.7 version. This release of Lucene introduced change for [compressed Binary doc values](https://github.com/apache/lucene-solr/commit/ce2959fe4cb1d1e77df04464c46004bf7846f6b5). As part of this change,  BinaryDecoder is added which returns the whole byte array for binary doc values with exact offset (position where the vector is stored) and length of bytes to be read, instead of slicing the byte array with just the bytes needed to decode vector.  

Before Lucene 8.5 (Elasticsearch version < 7.7)
https://github.com/apache/lucene-solr/blob/releases/lucene-solr/8.4.1/lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesProducer.java#L688

From Lucene 8.5 (Elasticsearch version >= 7.7)
https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/codecs/lucene80/Lucene80DocValuesProducer.java#L838-L840

Our [logic](https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/knn/index/codec/KNNCodecUtil.java#L48) to extract the float values(vector) from the ByteRef depends on sliced byte array and hence offset always points to 0 and length which is the size of sliced array.

Because of this issue, we always read the first vector for the whole compressed block and pass on the same vector to hnsw index resulting in duplicate points and scores which resulting in bad recall. This will be evident after the forcemerge

This fix needs to be backported to odfe1.8 and odfe1.9

**Comment by vamshin** [comment]
Fix here https://github.com/opendistro-for-elasticsearch/k-NN/pull/155/

**Comment by tanguilp** [comment]
Hi Vashmi! I've setup ODFE1.8 from the Docker image, and loaded a few thousand pieces of data with associated vectors.

When performing search requests, the same vector is always returned, and I get only one result.

Couldn't it be somehow related to this bug?

**Comment by vamshin** [comment]
@tanguilp you are right. This is related to this bug. We are in the process of updating artifacts

**Comment by vamshin** [comment]
This issue is now fixed in ODFE1.9

**Comment by timforr** [comment]
Was this fixed in ODFE1.8?

**Comment by vamshin** [comment]
@timforr this bug is fixed from 1.9.0 versions

**Comment by timforr** [comment]
@vamshin I'm looking to deploy to a managed AWS ES instance on Nov 2. It seems that the AWS ES only supports up to 1.8. So what are my options?

**Comment by vamshin** [comment]
> @vamshin I'm looking to deploy to a managed AWS ES instance on Nov 2. It seems that the AWS ES only supports up to 1.8. So what are my options?

@timforr this bug is backported to AWS ES 7.7 (odfe 1.8), 7.8(odfe 1.9) versions. So you should be good.
